// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmnsffquuqpujakglbsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtbnNmZnF1dXFwdWpha2dsYnNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMDYxOTIsImV4cCI6MjA1ODY4MjE5Mn0.5W4AF98POegBxfcXrEjE81-QM8P_SGpO-c6LqXMKEp0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);